// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaHanGHml4FEa4BKho5YzsKdCF0W8K05o',
    appId: '1:174052081155:web:189aeb3b49dd7b43db1836',
    messagingSenderId: '174052081155',
    projectId: 'nifty-96859',
    authDomain: 'nifty-96859.firebaseapp.com',
    storageBucket: 'nifty-96859.appspot.com',
    measurementId: 'G-J8LMDDK35W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeaamOVZHDREuAvCyecYUysJP9ohppO_M',
    appId: '1:179682000846:android:f78870d2f5d57f2019f59f',
    messagingSenderId: '179682000846',
    projectId: 'event-it-6c16f',
    storageBucket: 'event-it-6c16f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_uDKB4WsEchCybsGAw5_Mf8_vOThU83k',
    appId: '1:174052081155:ios:55f835e21e0293d1db1836',
    messagingSenderId: '174052081155',
    projectId: 'nifty-96859',
    storageBucket: 'nifty-96859.appspot.com',
    iosClientId:
        '174052081155-nulukif4oktg55knknrpp4bdmgrlktcn.apps.googleusercontent.com',
    iosBundleId: 'com.example.niftyMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_uDKB4WsEchCybsGAw5_Mf8_vOThU83k',
    appId: '1:174052081155:ios:55f835e21e0293d1db1836',
    messagingSenderId: '174052081155',
    projectId: 'nifty-96859',
    storageBucket: 'nifty-96859.appspot.com',
    iosClientId:
        '174052081155-nulukif4oktg55knknrpp4bdmgrlktcn.apps.googleusercontent.com',
    iosBundleId: 'com.example.niftyMobile',
  );
}
